# Generated by Django 5.1.6 on 2025-10-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='photos/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
